export const emailStyles = {
  body: {
    backgroundColor: '#f8fafc',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    margin: 0,
    padding: 0,
  },
  container: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    margin: '40px auto',
    maxWidth: '560px',
    padding: '48px 32px',
  },
  heading: {
    color: '#0f172a',
    fontSize: '24px',
    fontWeight: 600,
    lineHeight: '1.3',
    margin: '0 0 8px 0',
  },
  bodyText: {
    color: '#64748b',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: '1.6',
    margin: '0 0 16px 0',
  },
  itemTitle: {
    color: '#0f172a',
    fontSize: '15px',
    fontWeight: 600,
    lineHeight: '1.4',
    margin: '0 0 4px 0',
  },
  itemSummary: {
    color: '#64748b',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: '1.6',
    margin: '0 0 4px 0',
  },
  sourceAttribution: {
    color: '#94a3b8',
    fontSize: '13px',
    fontWeight: 400,
    lineHeight: '1.5',
    margin: '0 0 4px 0',
  },
  sectionLabel: {
    color: '#334155',
    fontSize: '12px',
    fontWeight: 600,
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
    lineHeight: '1.5',
    margin: '0 0 8px 0',
  },
  small: {
    color: '#94a3b8',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '1.5',
    textAlign: 'center' as const,
    margin: '0',
  },
  footerLink: {
    color: '#64748b',
    fontSize: '13px',
    fontWeight: 400,
    lineHeight: '1.5',
    margin: '0',
  },
  hr: {
    borderColor: '#e2e8f0',
    borderWidth: '1px',
    margin: '24px 0',
  },
  accent: '#3b82f6',
  ctaBox: {
    backgroundColor: '#f0f9ff',
    borderRadius: '8px',
    padding: '20px',
    margin: '0 0 0 0',
  },
  ctaButton: {
    backgroundColor: '#3b82f6',
    borderRadius: '6px',
    color: '#ffffff',
    display: 'inline-block',
    fontSize: '15px',
    fontWeight: 600,
    padding: '12px 24px',
    textDecoration: 'none',
  },
  feedbackMore: { color: '#16a34a', fontSize: '13px', fontWeight: 400, textDecoration: 'none' },
  feedbackLess: { color: '#dc2626', fontSize: '13px', fontWeight: 400, textDecoration: 'none' },
  feedbackSeparator: { color: '#94a3b8', fontSize: '13px' },
} as const
