import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Lucas Senechal",
  description:
    "Terms and conditions for using lucassenechal.com and the personalized AI newsletter service.",
};

export default function TermsOfServicePage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="last-updated">Last updated: February 20, 2026</p>

      <p>
        By using lucassenechal.com and subscribing to our newsletter service, you
        agree to these terms. If you do not agree, please do not use the service.
      </p>

      <h2>Service Description</h2>
      <ul>
        <li>
          We provide a free, AI-powered daily newsletter personalized to your
          interests and selected topics.
        </li>
        <li>
          Content is generated using automated research and AI synthesis from
          publicly available sources, with links back to original articles.
        </li>
        <li>
          We also offer consulting services accessible via the website.
        </li>
        <li>
          The service is provided free of charge and may be modified or
          discontinued at any time.
        </li>
      </ul>

      <h2>Account and Subscription</h2>
      <ul>
        <li>
          No account creation is required — your subscription is managed entirely
          via your email address.
        </li>
        <li>
          You can subscribe by providing your email address through the signup
          form on our website.
        </li>
        <li>
          You can unsubscribe at any time via the one-click unsubscribe link
          included in every email.
        </li>
        <li>
          We reserve the right to remove subscribers who abuse the service or
          violate these terms.
        </li>
      </ul>

      <h2>Content and Accuracy</h2>
      <ul>
        <li>
          Newsletter content is generated by AI and sourced from publicly
          available information across the web.
        </li>
        <li>
          We strive for accuracy but cannot guarantee that all information is
          correct, complete, or current. Content should not be relied upon as the
          sole source of truth.
        </li>
        <li>
          Links provided in newsletters point to third-party sources — we are not
          responsible for external content, accuracy, or availability.
        </li>
        <li>
          AI-generated estimates, analysis, and recommendations are informational
          only and do not constitute professional, financial, legal, or medical
          advice.
        </li>
      </ul>

      <h2>Acceptable Use</h2>
      <p>When using our service, you agree not to:</p>
      <ul>
        <li>Provide false or misleading information during signup.</li>
        <li>
          Use the service to collect, harvest, mine, or scrape data from our
          emails or website.
        </li>
        <li>
          Attempt to interfere with the service&apos;s operation, security, or
          infrastructure.
        </li>
        <li>
          Redistribute newsletter content commercially without prior written
          permission.
        </li>
        <li>
          Use automated tools or bots to interact with the signup or preference
          systems.
        </li>
      </ul>

      <h2>Intellectual Property</h2>
      <ul>
        <li>
          Newsletter content, website design, and branding are owned by Lucas
          Senechal unless otherwise noted.
        </li>
        <li>
          You may share newsletter content for personal, non-commercial use
          (e.g., forwarding to a friend, sharing a link on social media).
        </li>
        <li>
          Source content linked in newsletters belongs to their respective
          copyright holders and is subject to their terms.
        </li>
      </ul>

      <h2>SMS Terms</h2>
      <p>
        If you opt in to receive SMS summaries, the following additional terms
        apply:
      </p>
      <ul>
        <li>
          By opting in, you consent to receive automated text messages from us at
          the phone number you provide.
        </li>
        <li>
          <strong>Message frequency:</strong> Up to 1 message per day.
        </li>
        <li>
          <strong>Message and data rates may apply</strong> depending on your
          mobile carrier and plan.
        </li>
        <li>
          <strong>Opt out:</strong> Text <strong>STOP</strong> to any message to
          immediately stop receiving SMS.
        </li>
        <li>
          <strong>Help:</strong> Text <strong>HELP</strong> for support
          information, or email{" "}
          <a href="mailto:lucas@lucassenechal.com">lucas@lucassenechal.com</a>.
        </li>
        <li>
          SMS consent is not a condition of subscribing to the email newsletter.
        </li>
      </ul>

      <h2>Limitation of Liability</h2>
      <ul>
        <li>
          The service is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind, whether express or
          implied.
        </li>
        <li>
          We are not liable for any decisions made based on newsletter content,
          including but not limited to financial, professional, or personal
          decisions.
        </li>
        <li>
          We do not warrant that the service will be uninterrupted, timely,
          secure, or error-free.
        </li>
        <li>
          To the maximum extent permitted by law, our total liability is limited
          to the amount you have paid for the service. As this is a free service,
          maximum liability is $0.
        </li>
      </ul>

      <h2>Changes to Terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the service
        after changes constitutes acceptance of the new terms. Material changes
        that significantly affect your rights will be communicated via email to
        active subscribers at least 7 days before taking effect.
      </p>

      <h2>Governing Law</h2>
      <p>
        These terms are governed by and construed in accordance with applicable
        laws. Any disputes arising from these terms or your use of the service
        shall be resolved in accordance with those laws.
      </p>

      <h2>Contact</h2>
      <p>
        If you have questions about these terms or need support, contact us at:
      </p>
      <ul>
        <li>
          <strong>Email:</strong>{" "}
          <a href="mailto:lucas@lucassenechal.com">lucas@lucassenechal.com</a>
        </li>
      </ul>
    </>
  );
}
